name: Checkout

on:
  [workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build and test
        run: |
          npm install
          npm test
  
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: docker image build -t lukasprogress/cicd-demo .

      - name: Push image
        run: docker push lukasprogress/cicd-demo:latest


  bring_live:
    runs-on: [aws-ec2]

      steps:
        - name: fetch image
          run: docker pull lukasprogress/cicd-demo:latest

        - name: remove old container
          run: docker container rm -f server

        - name: run new container
          run: docker container run -p 3000:3000 -d --name server lukasprogress/cicd-demo:latest