name: Checkout

on:
  [push]

jobs:
  strategy:
    matrix:
      os: [windows-latest, ubuntu-latest, macOS-latest]
  build:
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        