name: Checkout

on:
  [push]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        checkout: [actions/checkout@v2, actions/checkout@v3, actions/checkout@v4]
        
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout
        uses: ${{ matrix.checkout }}
        